version: '3'

services:
  app:
    image: node:20
    container_name: socialswayer-members-api
    working_dir: /app
    volumes:
      - ./app:/app
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=letmein123
      - MYSQL_DATABASE=members
    command: sh -c "npm install && npx tsc && node dist/index.js"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: socialswayer-members-db
    environment:
      MYSQL_ROOT_PASSWORD: letmein123
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"